language: node_js
node_js:
- '12.13.0'
script:
- npm install
- npm test
- npm run deploy
cache:
  directories:
  - node_modules
env:
  global:
  - secure: MYqYHMRLTkhA119Zk/KegD+euVIleXuH38Ird9nPPey+5qnjKKsKy3JsxcW/TAE/oUQJmRRm0yUjk1bZ26qqN4VpE+vZhjJmhInLTrVGY3UlD7+uMdVGlffbJE3cVZk/ACvm9TpMIr5sv5X6BxSI1ahz/9lAxXaV3zDuNYW05Rs/DSleYu3KNLZVKXJfJU+Uq544zyqyYHCNP2iGFGRjU4ZG/QwE829HvBpmO/k3DAceXFCfELm3yata+CA7HjSmRgM+4Lr0/IwNVXqH30aYfylvtonF4yDVy866yzAshCww1RnSrhtm+pgpAPAejxY63TgukALhalz0s5W5msb/Ati0vWdGAI4o2HDx43YMojMchm++RKfzgwXZudF+nyJcQt5MB4sC8wvA6eVBR3h06PfLq+DXGq5rZf+EHSqYjvRK5KgA44NPIzYqty5nmvgt5SCCkz9Pw7DY7Pm3p8QRR95t9i2CKLMFSgLEKggDuMtM5sBBhp50vlk75e/q7VvhJkbtp4My5Ozr/ONCzwGETqKgb/lvNsxgo28XIquOUKmuOuJgcxOfPv1P3kfPCOTooMQDImiYCDxwJecZDg06L5c+051ZU+4r5Q7SzhB9fO3q0KC0GNUHHwfLfgLyuEbWz5GXwjWdhxvIS8l9Z9sUFHoJ1wPGnOGJbT/PZBpq/+4=
  - secure: ltjXO6/aJPtjm9QsiZ1COjsC9GrHcLZ5dORjn8c0qu/Qa4eAlXLh0LJ7qZYc08mw+otqX3yGuL2PD+leq1kZzps1qku/ZZ2L4d600y/h3fUlWghtsx+vG7HNFHjpotUtNmGwFXlxe6uCBQSQuf/nWzQlMMjQb9zT4Oh1+c1z67pJC/wrwltPg8A57ZHvLcMDfQHTCsStaNiO1zWZHwUujj4hezr9hD8zs3VQcorq0h5rDHB+oQx171p0vCh/rYHoYAmHuhf6YhyIuY45W2ISYME9WWN+CawFmCWnUY8jFeNTPhNJjZa2lzqfO+O2INodZB8C4WA3GlLl7N5PyKbNORiX/dOz94XCHHJf42jrOX2WQRHGbf7VtttCrk5u44zilEIe7xBA9GfSh9su37z1YZ8Zv+HuZFbShrOiqXJV56lHNIcp3NcYuKH6nUgsKhNo/IrA6e1DHJyWVRIg9RiO2Wy++0IC1uksG7d3Y+nNYUoujbgzqYx5NfmUg4aSwuuPhckjct2PPpj5MKrLTcwl/Jb0Mx2VZcZkk+lucuRlmkohe1UoNZdV3VPqNFGub6S6L3l1AItZgCyT7kNHOVEaErMlu+RVLfeRpDuUYEGxUtPsIFBPcm4YGuINnUBCbYB3YkTyV2Y1WpHdBPyzEHPjGCC7/fQSpZRP2LEidPCLO8I=
